version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: your-root-password
      MYSQL_DATABASE: car_wash
      MYSQL_USER: root
      MYSQL_PASSWORD: car_wash_user
    ports:
      - "3306:3306"
